### ISSUE TITLE
Reduce direct dependencies on database libraries

### ISSUE THREAD

**Issue by acburdine** [denali-js/denali-node-orm2#12]
Currently, denali-node-orm2 depends on 4 or 5 database modules directly (they are the ones supported by node-orm2). Because most apps using this addon will only use 1, the requirement of installing all 5 of them is unnecessary and results in extraneous dependencies.

However, it might be confusing to users if they don't know that their app must explicitly depend on whatever database module they need, so we should do two things to make this as easy to understand as possible.

- [ ] Write documentation saying that you must install the database module you need as a direct dependency of your app (and that it will not be automatically installed for you)
- [ ] The orm2-connect initializer should be updated to check that the configured database module is installed, and error out with a sane error message if it's not.

**Comment by acburdine** [comment]
After a bit more research, this unfortunately isn't possible. Node's require resolution won't go up past the root folder of this adapter, so even if we could ensure that the module was installed alongside this adapter, orm would still fail to connect b/c of the missing database dependency.

**Comment by davewasmer** [comment]
@acburdine are you sure about that? My reading of the [Modules docs](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) for Node is that Node will walk all the way up to the filesystem root looking for a node module.

**Comment by acburdine** [comment]
Hmm...I guess I could have been trolled by the fact that I had `denali-node-orm2` linked locally. I'll test by pushing a built branch and see what I can figure out

However, that wouldn't be great if this approach made it so you couldn't use denali-node-orm2 when you had it linked.
